# Also the name of the tenant, is used as the prefix for the topics 
# cmd - The command to open 
# event - Details of received and executed commands
# status - Telemetry about locker status
locker_name	=	lkaas

# MQTT Broker related settings
broker_port	=	8883
broker_user	=	devopstrends
broker_pass	=	C2g2d0s2012
keep_alive	= 	10

# TLS 
ca_cert		=	isrgrootx1.pem
ca_patsh	=	/opt/lkfw/

serial_port	=	/dev/ttyUSB0
pid_file	=	/tmp/lkfw.pid

