# Also the name of the tenant, is used as the prefix for the topics 
# cmd - The command to open 
# event - Details of received and executed commands
# status - Telemetry about locker status
locker_name	=	"lkaas"

# MQTT Broker related settings
broker_port	=	8883
broker_user	=	"devopstrends"
broker_pass	=	"C2g2d0s2012"
keep_alive	= 	10
post_seconds	=	1
broker_url	=	"95efa85031e142e69db9bbb994342b28.s1.eu.hivemq.cloud"

# TLS 
ca_cert		=	"lkfw.pem"
ca_path		=	"/opt/lkfw/"

serial_port	=	"/dev/ttyUSB0"
pid_file	=	"/tmp/lkfw.pid"

